export const A = {
  Open: 0,
  Close: 1,
  Run: 2,
  Exec: 3,
  Prepare: 4,
  StmtMeta: 5,
  StmtAll: 6,
  StmtGet: 7,
  StmtIterate: 8,
  StmtRun: 9,
  StmtValues: 10,
  StmtRaw: 11,
  StmtToString: 12,
  StmtFinalize: 13,
  InTransaction: 14,
  Filename: 15,
  Handle: 16,
  LoadExtension: 17,
  Serialize: 18,
  FileControl: 19,
} as const;
